### ISSUE TITLE
Scheduled Job disapears when I restart server

### ISSUE THREAD

**Issue by skanilabsinc** [contribsys/faktory-render#1]
Hi,

I have faktory installed on  render.com. it is working fine. But whenever the server restarts, all the scheduled jobs become 0. 

I really appreciate any help you can provide.

**Comment by mperham** [comment]
It sounds like the server has not been configured with persistent storage. It's possible it's running in a container and that container's local storage is reset on reboot. The Docker documentation talks about setting up persistent storage.

**Comment by mperham** [comment]
> Select an appropriate instance size and create a persistent disk for your data, mounted at /var/lib/faktory. See sizing notes below.

Did you create a persistent disk, per the README?

**Comment by skanilabsinc** [comment]
Thank you so much. I created a persistent disk. It is working fine now.
